### ISSUE TITLE
Error at boot with last two versions of MPMNDisabler.kext

### ISSUE THREAD

**Issue by dr3nan** [IOIIIO/MacProMemoryNotificationDisabler#6]
Hi there,

I have errors with the latest version of your .kext, I have compiled the latest 1.2 and still the issue persists here is the error log from system:

[MemorySlotNotification-crash.txt](https://github.com/IOIIIO/MacProMemoryNotificationDisabler/files/4306545/MemorySlotNotification-crash.txt)

**Comment by im-not-a-dev** [comment]
Yes sorry, I pushed a wrong patch. Should be fixed next commit.

**Comment by dr3nan** [comment]
Cheers!
