### ISSUE TITLE
Different warning in 'About this Mac'

### ISSUE THREAD

**Issue by wishie** [IOIIIO/MacProMemoryNotificationDisabler#7]
I get a warning about 'The installed memory modules are not arranged in a recommended configuration to provide optimal memory bandwidth'.

[https://cdn.discordapp.com/attachments/263798638373896203/711030526785355835/Screen_Shot_2020-05-16_at_11.41.18_am.png](https://cdn.discordapp.com/attachments/263798638373896203/711030526785355835/Screen_Shot_2020-05-16_at_11.41.18_am.png)

**Comment by im-not-a-dev** [comment]
This warning is not easily patchable, and generally correct in my testing.

**Comment by wishie** [comment]
I have 4 ram slots, and 4 ram modules made of 2 kits of 2x16Gb.

There really isn't any other way for them to be arranged.
